# Generated by Django 4.2.1 on 2025-11-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agnks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('waybill', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('column', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
            ],
        ),
    ]
